# Generated by Django 3.2 on 2024-12-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
