# Generated by Django 3.2 on 2024-12-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemodel',
            options={'ordering': ['-id']},
        ),
    ]
