# Generated by Django 3.2 on 2024-12-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_score'),
        ('reviews', '0004_auto_20241225_1923'),
    ]

    operations = [
    ]
