# Generated by Django 3.2 on 2024-12-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20241228_1907'),
        ('reviews', '0008_auto_20241228_2147'),
    ]

    operations = [
    ]
